server:
  error:
    include-stacktrace: on_param


spring:
  datasource:
    url: jdbc:mysql://root:OYcJ3DgFQXrBBQGEseQk@containers-us-west-154.railway.app:6147/railway?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: OYcJ3DgFQXrBBQGEseQk
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true