server:
  error:
    include-stacktrace: on_param

//informações para conexão do banco de dados
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/APIcomponentes?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update